{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:59:5)","timestamp":"2025-08-20 21:25:51"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\swagger.yaml'","path":"D:\\inventario-api\\src\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:26)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:06:07"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:06:08"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'","path":"D:\\inventario-api\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:12:26"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:12:26"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\swagger.yaml'","path":"D:\\inventario-api\\src\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:26)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:12:38"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:12:38"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'","path":"D:\\inventario-api\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:25)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:12:47"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:12:47"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'","path":"D:\\inventario-api\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:12:50"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:12:50"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'","path":"D:\\inventario-api\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:14:27"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:14:27"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'","path":"D:\\inventario-api\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:16:59"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:16:59"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'","path":"D:\\inventario-api\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:20:21"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:20:21"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\doc\\swagger.yaml'","path":"D:\\inventario-api\\src\\doc\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\doc\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:20:26"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:20:26"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\docs\\swagger.yaml'","path":"D:\\inventario-api\\src\\docs\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\docs\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:20:32"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:20:32"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\docs\\swagger.yaml'","path":"D:\\inventario-api\\src\\docs\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\docs\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:20:35"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:20:35"}
{"code":"ENOENT","errno":-4058,"level":"\u001b[31merror\u001b[39m","message":"Error al cargar el archivo YAML de Swagger: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\docs\\swagger.yaml'","path":"D:\\inventario-api\\src\\docs\\swagger.yaml","stack":"Error: ENOENT: no such file or directory, open 'D:\\inventario-api\\src\\docs\\swagger.yaml'\n    at Object.openSync (node:fs:596:3)\n    at Object.readFileSync (node:fs:464:35)\n    at Utils.getStringFromFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Utils.js:284:19)\n    at Yaml.parseFile (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:46:21)\n    at Yaml.load (D:\\inventario-api\\node_modules\\yamljs\\lib\\Yaml.js:78:17)\n    at Object.<anonymous> (D:\\inventario-api\\src\\app.js:24:27)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12)","syscall":"open","timestamp":"2025-08-21 11:20:46"}
{"level":"\u001b[31merror\u001b[39m","message":"Error al iniciar el servidor: Access denied for user 'root'@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)\n    at ConnectionManager.connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (D:\\inventario-api\\src\\app.js:124:5)","timestamp":"2025-08-21 11:20:47"}
{"level":"\u001b[31merror\u001b[39m","message":"Error en autenticación: invalid token","name":"JsonWebTokenError","stack":"JsonWebTokenError: invalid token\n    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:82:17)\n    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-08-21 11:40:06"}
{"body":{},"ip":"::1","level":"\u001b[31merror\u001b[39m","message":"Error en GET /api/products?page=1&limit=10: invalid token","params":{},"query":{"limit":"10","page":"1"},"stack":"JsonWebTokenError: invalid token\n    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:82:17)\n    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-08-21 11:40:06","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"}
{"level":"\u001b[31merror\u001b[39m","message":"Error en autenticación: invalid token","name":"JsonWebTokenError","stack":"JsonWebTokenError: invalid token\n    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:82:17)\n    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-08-21 11:40:31"}
{"body":{},"ip":"::1","level":"\u001b[31merror\u001b[39m","message":"Error en GET /api/purchases?page=1&limit=10: invalid token","params":{},"query":{"limit":"10","page":"1"},"stack":"JsonWebTokenError: invalid token\n    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:82:17)\n    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-08-21 11:40:31","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"}
{
  name: 'JsonWebTokenError',
  message: 'Error en autenticación: invalid signature',
  level: 'error',
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  timestamp: '2025-08-21 11:46:33'
}
{
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  body: {},
  params: {},
  query: { page: '1', limit: '10' },
  ip: '::1',
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
  level: 'error',
  message: 'Error en GET /api/products?page=1&limit=10: invalid signature',
  timestamp: '2025-08-21 11:46:33'
}
{
  name: 'JsonWebTokenError',
  message: 'Error en autenticación: invalid signature',
  level: 'error',
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  timestamp: '2025-08-21 11:53:32'
}
{
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  body: {},
  params: {},
  query: { page: '1', limit: '10' },
  ip: '::1',
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
  level: 'error',
  message: 'Error en GET /api/purchases?page=1&limit=10: invalid signature',
  timestamp: '2025-08-21 11:53:32'
}
{
  name: 'JsonWebTokenError',
  message: 'Error en autenticación: invalid signature',
  level: 'error',
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  timestamp: '2025-08-21 11:55:57'
}
{
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  userId: null,
  ip: '::1',
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
  body: {},
  level: 'error',
  message: 'Error en GET /api/purchases?page=1&limit=10: invalid signature',
  timestamp: '2025-08-21 11:55:57'
}
{
  name: 'JsonWebTokenError',
  message: 'Error en autenticación: invalid signature',
  level: 'error',
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  timestamp: '2025-08-21 12:14:05'
}
{
  stack: 'JsonWebTokenError: invalid signature\n' +
    '    at D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:171:19\n' +
    '    at getSecret (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:97:14)\n' +
    '    at module.exports [as verify] (D:\\inventario-api\\node_modules\\jsonwebtoken\\verify.js:101:10)\n' +
    '    at authenticate (D:\\inventario-api\\src\\middleware\\auth.js:22:25)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at next (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:149:13)\n' +
    '    at Route.dispatch (D:\\inventario-api\\node_modules\\express\\lib\\router\\route.js:119:3)\n' +
    '    at Layer.handle [as handle_request] (D:\\inventario-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
    '    at D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:284:15\n' +
    '    at Function.process_params (D:\\inventario-api\\node_modules\\express\\lib\\router\\index.js:346:12)',
  userId: null,
  ip: '::1',
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
  body: {},
  level: 'error',
  message: 'Error en GET /api/purchases?page=1&limit=10: invalid signature',
  timestamp: '2025-08-21 12:14:05'
}
{
  name: 'SequelizeValidationError',
  errors: [
    ValidationErrorItem {
      message: 'Purchase.numero_factura cannot be null',
      type: 'notNull Violation',
      path: 'numero_factura',
      value: null,
      origin: 'CORE',
      instance: Purchase {
        dataValues: {
          fecha_compra: 2025-08-21T21:53:04.990Z,
          estado: 'completada',
          id: null,
          user_id: 4,
          total: '1879.97',
          updatedAt: 2025-08-21T21:53:04.990Z,
          createdAt: 2025-08-21T21:53:04.990Z
        },
        _previousDataValues: { user_id: undefined, total: undefined },
        uniqno: 1,
        _changed: Set(2) { 'user_id', 'total' },
        _options: {
          isNewRecord: true,
          _schema: null,
          _schemaDelimiter: '',
          attributes: undefined,
          include: undefined,
          raw: undefined,
          silent: undefined
        },
        isNewRecord: true
      },
      validatorKey: 'is_null',
      validatorName: null,
      validatorArgs: []
    }
  ],
  level: 'error',
  message: 'Error al crear compra: notNull Violation: Purchase.numero_factura cannot be null',
  stack: 'SequelizeValidationError: notNull Violation: Purchase.numero_factura cannot be null\n' +
    '    at InstanceValidator._validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async InstanceValidator._validateAndRunHooks (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n' +
    '    at async InstanceValidator.validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2426:7)\n' +
    '    at async Purchase.create (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:1362:12)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:80:22',
  timestamp: '2025-08-21 16:53:04'
}
{
  stack: 'SequelizeValidationError: notNull Violation: Purchase.numero_factura cannot be null\n' +
    '    at InstanceValidator._validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async InstanceValidator._validateAndRunHooks (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n' +
    '    at async InstanceValidator.validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2426:7)\n' +
    '    at async Purchase.create (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:1362:12)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:80:22',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 1, cantidad: 2 }, { product_id: 3, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: notNull Violation: Purchase.numero_factura cannot be null',
  timestamp: '2025-08-21 16:53:05'
}
{
  name: 'SequelizeValidationError',
  errors: [
    ValidationErrorItem {
      message: 'Purchase.numero_factura cannot be null',
      type: 'notNull Violation',
      path: 'numero_factura',
      value: null,
      origin: 'CORE',
      instance: Purchase {
        dataValues: {
          fecha_compra: 2025-08-21T22:00:53.741Z,
          estado: 'completada',
          id: null,
          user_id: 4,
          total: '2759.97',
          updatedAt: 2025-08-21T22:00:53.741Z,
          createdAt: 2025-08-21T22:00:53.741Z
        },
        _previousDataValues: { user_id: undefined, total: undefined },
        uniqno: 1,
        _changed: Set(2) { 'user_id', 'total' },
        _options: {
          isNewRecord: true,
          _schema: null,
          _schemaDelimiter: '',
          attributes: undefined,
          include: undefined,
          raw: undefined,
          silent: undefined
        },
        isNewRecord: true
      },
      validatorKey: 'is_null',
      validatorName: null,
      validatorArgs: []
    }
  ],
  level: 'error',
  message: 'Error al crear compra: notNull Violation: Purchase.numero_factura cannot be null',
  stack: 'SequelizeValidationError: notNull Violation: Purchase.numero_factura cannot be null\n' +
    '    at InstanceValidator._validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async InstanceValidator._validateAndRunHooks (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n' +
    '    at async InstanceValidator.validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2426:7)\n' +
    '    at async Purchase.create (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:1362:12)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:80:22',
  timestamp: '2025-08-21 17:00:53'
}
{
  stack: 'SequelizeValidationError: notNull Violation: Purchase.numero_factura cannot be null\n' +
    '    at InstanceValidator._validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async InstanceValidator._validateAndRunHooks (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n' +
    '    at async InstanceValidator.validate (D:\\inventario-api\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2426:7)\n' +
    '    at async Purchase.create (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:1362:12)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:80:22',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: notNull Violation: Purchase.numero_factura cannot be null',
  timestamp: '2025-08-21 17:00:53'
}
{
  error: 'Lock wait timeout exceeded; try restarting transaction',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.update (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:355:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2490:35)\n' +
    '    at async Product.reducirStock (D:\\inventario-api\\src\\models\\Product.js:120:3)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:126:9',
  userId: 4,
  productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ],
  level: 'error',
  message: 'Error al crear compra:',
  timestamp: '2025-08-21 17:12:55'
}
{
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.update (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:355:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2490:35)\n' +
    '    at async Product.reducirStock (D:\\inventario-api\\src\\models\\Product.js:120:3)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:126:9',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: Lock wait timeout exceeded; try restarting transaction',
  timestamp: '2025-08-21 17:12:55'
}
{
  error: 'Lock wait timeout exceeded; try restarting transaction',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.update (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:355:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2490:35)\n' +
    '    at async Product.reducirStock (D:\\inventario-api\\src\\models\\Product.js:120:3)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:126:9',
  userId: 4,
  productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ],
  level: 'error',
  message: 'Error al crear compra:',
  timestamp: '2025-08-21 17:19:34'
}
{
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.update (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:355:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2490:35)\n' +
    '    at async Product.reducirStock (D:\\inventario-api\\src\\models\\Product.js:120:3)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:126:9',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: Lock wait timeout exceeded; try restarting transaction',
  timestamp: '2025-08-21 17:19:34'
}
{
  error: 'Lock wait timeout exceeded; try restarting transaction',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.update (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:355:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2490:35)\n' +
    '    at async Product.reducirStock (D:\\inventario-api\\src\\models\\Product.js:120:3)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:126:9',
  userId: 4,
  productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ],
  level: 'error',
  message: 'Error al crear compra:',
  timestamp: '2025-08-21 17:38:56'
}
{
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.update (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:355:12)\n' +
    '    at async model.save (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:2490:35)\n' +
    '    at async Product.reducirStock (D:\\inventario-api\\src\\models\\Product.js:120:3)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:126:9',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: Lock wait timeout exceeded; try restarting transaction',
  timestamp: '2025-08-21 17:38:56'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_72`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_72`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_72`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_72`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_72`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:44:22'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:45:06'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:45:06'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:45:06'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_74`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_74`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_74`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_74`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_74`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:45:07'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:46:22'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:46:22'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:46:22'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_77`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_77`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_77`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_77`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_77`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:46:23'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:46:58'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:46:58'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:46:58'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7b`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7b`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7b`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7b`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7b`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:46:59'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:47:22'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:47:22'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:47:22'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7d`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7d`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7d`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7d`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_7d`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:47:23'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:48:04'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:48:04'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:48:04'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_80`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_80`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_80`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_80`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_80`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:48:05'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:48:35'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:48:35'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:48:35'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_83`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_83`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_83`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_83`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_83`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:48:36'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_86`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_86`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_86`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_86`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_86`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:51:42'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_89`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_89`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_89`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_89`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_89`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:52:13'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:54:42'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:54:42'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:54:42'
}
{
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_8c`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_8c`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_8c`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_8c`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
    parameters: undefined
  },
  sql: 'ALTER TABLE `purchases` ADD FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;',
  parameters: {},
  table: 'users',
  fields: [ 'user_id' ],
  value: undefined,
  index: 'purchases_ibfk_1',
  reltype: 'child',
  level: 'error',
  message: 'Error al iniciar servidor: Cannot add or update a child row: a foreign key constraint fails (`inventario_db`.`#sql-18cc_8c`, CONSTRAINT `purchases_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Purchase.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\model.js:984:11)\n' +
    '    at async Sequelize.sync (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:377:9)\n' +
    '    at async startServer (D:\\inventario-api\\src\\app.js:89:7)',
  timestamp: '2025-08-21 17:54:42'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:57:20'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:57:20'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 17:57:20'
}
{
  error: Error
      at Query.run (D:\inventario-api\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
      at D:\inventario-api\node_modules\sequelize\lib\sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MySQLQueryInterface.setIsolationLevel (D:\inventario-api\node_modules\sequelize\lib\dialects\abstract\query-interface.js:517:12)
      at async Transaction.begin (D:\inventario-api\node_modules\sequelize\lib\transaction.js:114:5)
      at async Transaction.prepareEnvironment (D:\inventario-api\node_modules\sequelize\lib\transaction.js:89:7)
      at async Sequelize.transaction (D:\inventario-api\node_modules\sequelize\lib\sequelize.js:500:7)
      at async D:\inventario-api\src\routes\purchases.js:23:23 {
    name: 'SequelizeDatabaseError',
    parent: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1
        at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
        at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
        at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
        at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
        at Socket.emit (node:events:517:28)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)
        at Readable.push (node:internal/streams/readable:278:10) {
      code: 'ER_PARSE_ERROR',
      errno: 1064,
      sqlState: '42000',
      sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1",
      sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
      parameters: undefined
    },
    original: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1
        at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
        at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
        at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
        at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
        at Socket.emit (node:events:517:28)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)
        at Readable.push (node:internal/streams/readable:278:10) {
      code: 'ER_PARSE_ERROR',
      errno: 1064,
      sqlState: '42000',
      sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1",
      sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
      parameters: undefined
    },
    sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
    parameters: {}
  },
  level: 'error',
  message: "unhandledRejection: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1\n" +
    'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.setIsolationLevel (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:517:12)\n' +
    '    at async Transaction.begin (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:114:5)\n' +
    '    at async Transaction.prepareEnvironment (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:89:7)\n' +
    '    at async Sequelize.transaction (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:500:7)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:23:23',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.setIsolationLevel (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:517:12)\n' +
    '    at async Transaction.begin (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:114:5)\n' +
    '    at async Transaction.prepareEnvironment (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:89:7)\n' +
    '    at async Sequelize.transaction (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:500:7)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:23:23',
  rejection: true,
  date: 'Thu Aug 21 2025 17:57:27 GMT-0500 (hora estándar de Colombia)',
  process: {
    pid: 11676,
    uid: null,
    gid: null,
    cwd: 'D:\\inventario-api',
    execPath: 'C:\\nvm4w\\nodejs\\node.exe',
    version: 'v18.20.0',
    argv: [
      'C:\\nvm4w\\nodejs\\node.exe',
      'D:\\inventario-api\\src\\app.js'
    ],
    memoryUsage: {
      rss: 86421504,
      heapTotal: 61366272,
      heapUsed: 28792920,
      external: 1352433,
      arrayBuffers: 83775
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 31434.937 },
  trace: [
    {
      column: 25,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js',
      function: 'Query.run',
      line: 52,
      method: 'run',
      native: false
    },
    {
      column: 28,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js',
      function: null,
      line: 315,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/process/task_queues',
      function: 'process.processTicksAndRejections',
      line: 95,
      method: 'processTicksAndRejections',
      native: false
    },
    {
      column: 12,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js',
      function: 'async MySQLQueryInterface.setIsolationLevel',
      line: 517,
      method: 'setIsolationLevel',
      native: false
    },
    {
      column: 5,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js',
      function: 'async Transaction.begin',
      line: 114,
      method: 'begin',
      native: false
    },
    {
      column: 7,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js',
      function: 'async Transaction.prepareEnvironment',
      line: 89,
      method: 'prepareEnvironment',
      native: false
    },
    {
      column: 7,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js',
      function: 'async Sequelize.transaction',
      line: 500,
      method: 'transaction',
      native: false
    },
    {
      column: 23,
      file: 'async D:\\inventario-api\\src\\routes\\purchases.js',
      function: null,
      line: 23,
      method: null,
      native: false
    }
  ],
  timestamp: '2025-08-21 17:57:27'
}
{
  error: 'product is not defined',
  stack: 'ReferenceError: product is not defined\n' +
    '    at D:\\inventario-api\\src\\routes\\purchases.js:114:7\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  userId: 4,
  productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ],
  level: 'error',
  message: 'Error al crear compra:',
  timestamp: '2025-08-21 18:04:48'
}
{
  stack: 'ReferenceError: product is not defined\n' +
    '    at D:\\inventario-api\\src\\routes\\purchases.js:114:7\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: product is not defined',
  timestamp: '2025-08-21 18:04:49'
}
{
  error: 'product is not defined',
  stack: 'ReferenceError: product is not defined\n' +
    '    at D:\\inventario-api\\src\\routes\\purchases.js:114:7\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  userId: 4,
  productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ],
  level: 'error',
  message: 'Error al crear compra:',
  timestamp: '2025-08-21 18:05:18'
}
{
  stack: 'ReferenceError: product is not defined\n' +
    '    at D:\\inventario-api\\src\\routes\\purchases.js:114:7\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  userId: 4,
  ip: '::1',
  userAgent: 'PostmanRuntime/7.45.0',
  body: {
    productos: [ { product_id: 9, cantidad: 2 }, { product_id: 8, cantidad: 1 } ]
  },
  level: 'error',
  message: 'Error en POST /api/purchases: product is not defined',
  timestamp: '2025-08-21 18:05:18'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 18:21:01'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 18:21:01'
}
{
  level: 'error',
  message: "Error configurando sesión MySQL: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper",
  stack: "Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://sidorares.github.io/node-mysql2/docs#using-promise-wrapper, or the mysql2 documentation at https://sidorares.github.io/node-mysql2/docs/documentation/promise-wrapper\n" +
    '    at Query.then (D:\\inventario-api\\node_modules\\mysql2\\lib\\commands\\query.js:44:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  timestamp: '2025-08-21 18:21:01'
}
{
  error: Error
      at Query.run (D:\inventario-api\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
      at D:\inventario-api\node_modules\sequelize\lib\sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MySQLQueryInterface.setIsolationLevel (D:\inventario-api\node_modules\sequelize\lib\dialects\abstract\query-interface.js:517:12)
      at async Transaction.begin (D:\inventario-api\node_modules\sequelize\lib\transaction.js:114:5)
      at async Transaction.prepareEnvironment (D:\inventario-api\node_modules\sequelize\lib\transaction.js:89:7)
      at async Sequelize.transaction (D:\inventario-api\node_modules\sequelize\lib\sequelize.js:500:7)
      at async D:\inventario-api\src\routes\purchases.js:19:23 {
    name: 'SequelizeDatabaseError',
    parent: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1
        at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
        at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
        at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
        at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
        at Socket.emit (node:events:517:28)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)
        at Readable.push (node:internal/streams/readable:278:10) {
      code: 'ER_PARSE_ERROR',
      errno: 1064,
      sqlState: '42000',
      sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1",
      sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
      parameters: undefined
    },
    original: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1
        at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
        at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
        at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
        at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
        at Socket.emit (node:events:517:28)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)
        at Readable.push (node:internal/streams/readable:278:10) {
      code: 'ER_PARSE_ERROR',
      errno: 1064,
      sqlState: '42000',
      sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1",
      sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
      parameters: undefined
    },
    sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
    parameters: {}
  },
  level: 'error',
  message: "unhandledRejection: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1\n" +
    'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.setIsolationLevel (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:517:12)\n' +
    '    at async Transaction.begin (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:114:5)\n' +
    '    at async Transaction.prepareEnvironment (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:89:7)\n' +
    '    at async Sequelize.transaction (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:500:7)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:19:23',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.setIsolationLevel (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:517:12)\n' +
    '    at async Transaction.begin (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:114:5)\n' +
    '    at async Transaction.prepareEnvironment (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:89:7)\n' +
    '    at async Sequelize.transaction (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:500:7)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:19:23',
  rejection: true,
  date: 'Thu Aug 21 2025 18:21:19 GMT-0500 (hora estándar de Colombia)',
  process: {
    pid: 21240,
    uid: null,
    gid: null,
    cwd: 'D:\\inventario-api',
    execPath: 'C:\\nvm4w\\nodejs\\node.exe',
    version: 'v18.20.0',
    argv: [
      'C:\\nvm4w\\nodejs\\node.exe',
      'D:\\inventario-api\\src\\app.js'
    ],
    memoryUsage: {
      rss: 62853120,
      heapTotal: 27095040,
      heapUsed: 25386064,
      external: 1428321,
      arrayBuffers: 162366
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 32867.812 },
  trace: [
    {
      column: 25,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js',
      function: 'Query.run',
      line: 52,
      method: 'run',
      native: false
    },
    {
      column: 28,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js',
      function: null,
      line: 315,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/process/task_queues',
      function: 'process.processTicksAndRejections',
      line: 95,
      method: 'processTicksAndRejections',
      native: false
    },
    {
      column: 12,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js',
      function: 'async MySQLQueryInterface.setIsolationLevel',
      line: 517,
      method: 'setIsolationLevel',
      native: false
    },
    {
      column: 5,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js',
      function: 'async Transaction.begin',
      line: 114,
      method: 'begin',
      native: false
    },
    {
      column: 7,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js',
      function: 'async Transaction.prepareEnvironment',
      line: 89,
      method: 'prepareEnvironment',
      native: false
    },
    {
      column: 7,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js',
      function: 'async Sequelize.transaction',
      line: 500,
      method: 'transaction',
      native: false
    },
    {
      column: 23,
      file: 'async D:\\inventario-api\\src\\routes\\purchases.js',
      function: null,
      line: 19,
      method: null,
      native: false
    }
  ],
  timestamp: '2025-08-21 18:21:19'
}
{
  error: Error
      at Query.run (D:\inventario-api\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
      at D:\inventario-api\node_modules\sequelize\lib\sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MySQLQueryInterface.setIsolationLevel (D:\inventario-api\node_modules\sequelize\lib\dialects\abstract\query-interface.js:517:12)
      at async Transaction.begin (D:\inventario-api\node_modules\sequelize\lib\transaction.js:114:5)
      at async Transaction.prepareEnvironment (D:\inventario-api\node_modules\sequelize\lib\transaction.js:89:7)
      at async Sequelize.transaction (D:\inventario-api\node_modules\sequelize\lib\sequelize.js:500:7)
      at async D:\inventario-api\src\routes\purchases.js:19:23 {
    name: 'SequelizeDatabaseError',
    parent: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1
        at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
        at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
        at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
        at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
        at Socket.emit (node:events:517:28)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)
        at Readable.push (node:internal/streams/readable:278:10) {
      code: 'ER_PARSE_ERROR',
      errno: 1064,
      sqlState: '42000',
      sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1",
      sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
      parameters: undefined
    },
    original: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1
        at Packet.asError (D:\inventario-api\node_modules\mysql2\lib\packets\packet.js:740:17)
        at Query.execute (D:\inventario-api\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:475:34)
        at PacketParser.onPacket (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:93:12)
        at PacketParser.executeStart (D:\inventario-api\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\inventario-api\node_modules\mysql2\lib\base\connection.js:100:25)
        at Socket.emit (node:events:517:28)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)
        at Readable.push (node:internal/streams/readable:278:10) {
      code: 'ER_PARSE_ERROR',
      errno: 1064,
      sqlState: '42000',
      sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1",
      sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
      parameters: undefined
    },
    sql: 'SET TRANSACTION ISOLATION LEVEL READ_COMMITTED;',
    parameters: {}
  },
  level: 'error',
  message: "unhandledRejection: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'READ_COMMITTED' at line 1\n" +
    'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.setIsolationLevel (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:517:12)\n' +
    '    at async Transaction.begin (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:114:5)\n' +
    '    at async Transaction.prepareEnvironment (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:89:7)\n' +
    '    at async Sequelize.transaction (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:500:7)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:19:23',
  stack: 'Error\n' +
    '    at Query.run (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n' +
    '    at D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async MySQLQueryInterface.setIsolationLevel (D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:517:12)\n' +
    '    at async Transaction.begin (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:114:5)\n' +
    '    at async Transaction.prepareEnvironment (D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js:89:7)\n' +
    '    at async Sequelize.transaction (D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js:500:7)\n' +
    '    at async D:\\inventario-api\\src\\routes\\purchases.js:19:23',
  rejection: true,
  date: 'Thu Aug 21 2025 18:27:11 GMT-0500 (hora estándar de Colombia)',
  process: {
    pid: 2148,
    uid: null,
    gid: null,
    cwd: 'D:\\inventario-api',
    execPath: 'C:\\nvm4w\\nodejs\\node.exe',
    version: 'v18.20.0',
    argv: [
      'C:\\nvm4w\\nodejs\\node.exe',
      'D:\\inventario-api\\src\\app.js'
    ],
    memoryUsage: {
      rss: 63258624,
      heapTotal: 27357184,
      heapUsed: 25309816,
      external: 1428321,
      arrayBuffers: 162366
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 33219.656 },
  trace: [
    {
      column: 25,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js',
      function: 'Query.run',
      line: 52,
      method: 'run',
      native: false
    },
    {
      column: 28,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js',
      function: null,
      line: 315,
      method: null,
      native: false
    },
    {
      column: 5,
      file: 'node:internal/process/task_queues',
      function: 'process.processTicksAndRejections',
      line: 95,
      method: 'processTicksAndRejections',
      native: false
    },
    {
      column: 12,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js',
      function: 'async MySQLQueryInterface.setIsolationLevel',
      line: 517,
      method: 'setIsolationLevel',
      native: false
    },
    {
      column: 5,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js',
      function: 'async Transaction.begin',
      line: 114,
      method: 'begin',
      native: false
    },
    {
      column: 7,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\transaction.js',
      function: 'async Transaction.prepareEnvironment',
      line: 89,
      method: 'prepareEnvironment',
      native: false
    },
    {
      column: 7,
      file: 'D:\\inventario-api\\node_modules\\sequelize\\lib\\sequelize.js',
      function: 'async Sequelize.transaction',
      line: 500,
      method: 'transaction',
      native: false
    },
    {
      column: 23,
      file: 'async D:\\inventario-api\\src\\routes\\purchases.js',
      function: null,
      line: 19,
      method: null,
      native: false
    }
  ],
  timestamp: '2025-08-21 18:27:11'
}
